_wandb:
    value:
        cli_version: 0.22.2
        e:
            xsepyik67qfbd5itjh3yohigvn6d1t3m:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "35965706240"
                        used: "25088364544"
                email: 112201026@smail.iitpkd.ac.in
                executable: /usr/bin/python3
                git:
                    commit: cc1347c4a41c6157b080b2359fd092b1f05b5f99
                    remote: git@github.com:GBhavaniShankar/mlops2025w_112201026.git
                host: Vivobook
                memory:
                    total: "8003772416"
                os: Linux-5.15.0-160-generic-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.10.12
                root: /home/bhavani/Desktop/sem_7/MLOps/mlops2025w_112201026/Class/week10
                startedAt: "2025-10-28T05:41:37.947234Z"
                writerId: xsepyik67qfbd5itjh3yohigvn6d1t3m
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
n_estimators:
    value: 50
random_state:
    value: 42
