_wandb:
    value:
        cli_version: 0.22.2
        e:
            lzd6sfgohdja9qzcueeu8vlfxmx8lrjq:
                codePath: Class/week8/wandb_cloud_deploy_lab_detailed.ipynb
                codePathLocal: wandb_cloud_deploy_lab_detailed.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "35965706240"
                        used: "24673849344"
                email: 112201026@smail.iitpkd.ac.in
                executable: /usr/bin/python3
                git:
                    commit: 3ae1928f8002e95686c84a397bb2f48c33d7864e
                    remote: git@github.com:GBhavaniShankar/mlops2025w_112201026.git
                host: Vivobook
                memory:
                    total: "8003772416"
                os: Linux-5.15.0-160-generic-x86_64-with-glibc2.35
                program: wandb_cloud_deploy_lab_detailed.ipynb
                python: CPython 3.10.12
                root: /home/bhavani/Desktop/sem_7/MLOps/mlops2025w_112201026/Class/week8
                startedAt: "2025-10-21T14:27:16.122477Z"
                writerId: lzd6sfgohdja9qzcueeu8vlfxmx8lrjq
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": linux-x86_64
